#!/bin/bash


SINK=$(pactl list sinks short | grep RUNNING | sed -e 's,^\([0-9][0-9]*\)[^0-9].*,\1,')
VOLUME=$(pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')
MUTE=$(pactl list sinks | grep '^[[:space:]]Mute:' | head -n $(( $SINK + 1 )) | tail -n 1 | awk ' {print $2}')
COLOR="#AAAAAA"


if [[ ${VOLUME} -gt 100 ]]; then
	COLOR="#FAAA00"
fi


if [[ "${MUTE}" == "no" ]]; then
	echo "${VOLUME}%"
	echo "${VOLUME}%"
	echo "${COLOR}"
elif [[ "${MUTE}" == "yes" ]]; then
	echo ""
	echo ""
	echo "#FAAA00"
else 
	echo "?"
	echo "?"
	echo "#FAAA00"
fi


# mouse buttons
case $BLOCK_BUTTON in
    1) pactl set-sink-mute $SINK toggle ;;
    3) pavucontrol ;;
	4) pactl set-sink-volume $SINK +5% ;;
	5) pactl set-sink-volume $SINK -5% ;;
esac