#!/bin/bash
DEVICE="--"
DEVICE=$(echo -e 'info\nquit' | bluetoothctl | awk '/Name/ {print $2}')
PROFILE=$(pactl list | grep "Active Profile:" | awk '{print $NF}' | grep -e headset_head_unit  -e a2dp_sink_aac)

#🎤🎧
case $PROFILE in 
	headset_head_unit) ICON=;; 
	a2dp_sink_aac) ICON=;;
	*) ICON="";;
esac

if [[ -z "${DEVICE}" ]]; then
	echo "--"
	echo "--"
	echo ""
else
	echo "$DEVICE $ICON"
	echo "$DEVICE $ICON"
	echo ""
fi


if [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
 blueman-manager
fi