#!/usr/bin/env bash
LNG=$(xkblayout-state print %s | awk '{print toupper($0)}')
case $LNG in
  "US")
    CLR=\#AAAAAA ;; # green
  "SK")
    CLR=\#FAAA00 ;; # red
  *)
    CLR=\#FAAA00 ;; # all others default-white
esac
echo "$LNG"
echo "$LNG"
echo "$CLR"

if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
 xkblayout-state set +1
fi